baseURL = 'https://asdrome.com/'
title = 'Asdrome'
defaultContentLanguage = 'es'
defaultContentLanguageInSubdir = false
theme = 'material-hugo'

sectionPagesMenu = 'main'

[module]
  [module.hugoVersion]
    extended = true
    min = "0.122.0"

[languages]
  [languages.es]
    contentDir = 'content/es'
    disabled = false
    languageCode = 'es'
    languageDirection = 'ltr'
    languageName = 'Español'
    weight = 1

  [languages.en]
    contentDir = 'content/en'
    disabled = true
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 2
