baseURL = 'https://asdrome.com/'
title = 'Asdrome'
languageCode = 'es'
defaultContentLanguage = 'es'
theme = 'material-hugo'


[module]
  [module.hugoVersion]
    extended = false
    min = "0.122.0"

[languages]
  [languages.es]
    languageName= 'Español'
    contentDir= 'content/es'
    weight= 1
    disabled= false
  [languages.en]
    languageName= 'English'
    contentDir= 'content/en'
    weight= 2
    disabled= true
